name: latexmk
on:
  push:
    tags:
      - "*"
jobs:
  latexmk:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: yegor256/latexmk-action@0.13.0
        with:
          cmd: latexmk
          path: src
          opts: -pdf
          packages: acmart tikz lipsum mdframed graphicx url import
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release.tar.gz,src/article.pdf"
          generateReleaseNotes: true
          makeLatest: true
