name: Build LaTeX document
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Article
        uses: hspaans/latexmk-action@v2.0.0
        with:
          format: pdf
          filename: src/article.tex
          options: -cd -pdf -synctex=1 -interaction=nonstopmode -file-line-error

      - name: Bump Version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Article
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          generate_release_notes: true
          files: src/article.pdf
